### ISSUE TITLE
atom typing dataset

### ISSUE THREAD

**Issue by yuanqing-wang** [choderalab/hgfp#5]
@maxentile actually, do you mind if you could open the PR back again for the data pipeline for atom types?

I just figured that it would be faster since you're much more familiar with those. I'll continue my model shopping for now.

**Comment by maxentile** [comment]
There were a couple important problems mentioned in https://github.com/choderalab/hgfp/pull/4 -- I mistakenly indexed by SMILES even though that's a bad idea, and I don't want to commit a large binary file we'll need to overwrite. Aiming to open a fresh PR in the next couple days that only has an iterator, as you suggested, compatible with the other datasets.

In the meantime if you want an example script for generating vdw atom-typing masks, feel free to adapt this function: https://github.com/choderalab/hgfp/pull/4/files#diff-0cb20440198033d9e59457778d5432ceR31-R40 .

**Comment by maxentile** [comment]
Closed via https://github.com/choderalab/hgfp/pull/6
